### ISSUE TITLE
Can't compile on rust 1.1

### ISSUE THREAD

**Issue by xmao** [murarth/rusti#41]
Rusti can't compiled on Rust 1.1. Can anybody help?

src/rusti/exec.rs:21:5: 21:19 error: unresolved import `rustc::ast_map`. There is no `ast_map` in `rustc`
src/rusti/exec.rs:21 use rustc::ast_map;
                         ^~~~~~~~~~~~~~
src/rusti/exec.rs:32:5: 32:43 error: unresolved import `syntax::feature_gate::UnstableFeatures`. There is no `UnstableFeatures` in `syntax::feature_gate`
src/rusti/exec.rs:32 use syntax::feature_gate::UnstableFeatures;
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `rusti`.

**Comment by murarth** [comment]
Are you using the latest nightly build of Rust? If not, you should update using [rustup](https://github.com/rust-lang/rustup) with `--channel=nightly`.
