### ISSUE TITLE
Build fails on arm linux

### ISSUE THREAD

**Issue by petevine** [murarth/rusti#63]
Trying to build with an `armv7` 1.7 nightly from about a week ago, I'm getting this error:

````
Compiling rusti v0.0.1 (file:///tmp/rusti-master)
src/rusti/input.rs:26:22: 26:33 error: unresolved import `syntax::errors::ColorConfig`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:26 use syntax::errors::{ColorConfig, Handler, Level, RenderSpan};
                                           ^~~~~~~~~~~
src/rusti/input.rs:26:22: 26:33 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:28:5: 28:30 error: unresolved import `syntax::errors::Level::*`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:28 use syntax::errors::Level::*;
                          ^~~~~~~~~~~~~~~~~~~~~~~~~
src/rusti/input.rs:28:5: 28:30 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:27:40: 27:53 error: unresolved import `syntax::errors::emitter::EmitterWriter`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:27 use syntax::errors::emitter::{Emitter, EmitterWriter};
                                                             ^~~~~~~~~~~~~
src/rusti/input.rs:27:40: 27:53 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:27:31: 27:38 error: unresolved import `syntax::errors::emitter::Emitter`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:27 use syntax::errors::emitter::{Emitter, EmitterWriter};
                                                    ^~~~~~~
src/rusti/input.rs:27:31: 27:38 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:26:51: 26:61 error: unresolved import `syntax::errors::RenderSpan`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:26 use syntax::errors::{ColorConfig, Handler, Level, RenderSpan};
                                                                        ^~~~~~~~~~
src/rusti/input.rs:26:51: 26:61 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:26:44: 26:49 error: unresolved import `syntax::errors::Level`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:26 use syntax::errors::{ColorConfig, Handler, Level, RenderSpan};
                                                                 ^~~~~
src/rusti/input.rs:26:44: 26:49 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/input.rs:26:35: 26:42 error: unresolved import `syntax::errors::Handler`. Could not find `errors` in `syntax` [E0432]
src/rusti/input.rs:26 use syntax::errors::{ColorConfig, Handler, Level, RenderSpan};
                                                        ^~~~~~~
src/rusti/input.rs:26:35: 26:42 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/exec.rs:37:5: 37:19 error: unresolved import `syntax::errors`. There is no `errors` in `syntax` [E0432]
src/rusti/exec.rs:37 use syntax::errors;
                         ^~~~~~~~~~~~~~
src/rusti/exec.rs:37:5: 37:19 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/exec.rs:38:40: 38:52 error: unresolved import `syntax::errors::emitter::BasicEmitter`. Could not find `errors` in `syntax` [E0432]
src/rusti/exec.rs:38 use syntax::errors::emitter::{Emitter, BasicEmitter};
                                                            ^~~~~~~~~~~~
src/rusti/exec.rs:38:40: 38:52 help: run `rustc --explain E0432` to see a detailed explanation
src/rusti/exec.rs:38:31: 38:38 error: unresolved import `syntax::errors::emitter::Emitter`. Could not find `errors` in `syntax` [E0432]
src/rusti/exec.rs:38 use syntax::errors::emitter::{Emitter, BasicEmitter};
                                                   ^~~~~~~
src/rusti/exec.rs:38:31: 38:38 help: run `rustc --explain E0432` to see a detailed explanation
error: aborting due to 10 previous errors
Could not compile `rusti`.
````

**Comment by murarth** [comment]
I've just checked and rusti builds successfully with the latest nightly, `(0c7c94e8a 2015-12-26)`.

You can look at the commit logs to see when changes have been made to support a new nightly build. If your nightly is older than the most recent fix, you can either use an older revision of rusti or download a new nightly build.
